Repository atom-community/apm, pull requests merged in 2020-09, with the labels that each got.

#26 Respect the --verbose flag for `apm install`
  src/install.coffee
Labels: enhancement

#36 Use Scripts instead of Grunt
  Gruntfile.coffee
  package-lock.json
  package.json
Labels: Build, Modernization, enhancement

#28 Use GitHub Actions to test Windows x86
  .github/workflows/CI.yml
  appveyor.yml
Labels: CI

#48 Optimize getResourcePath
  src/apm.coffee
Labels: enhancement

#49 Use ES6 syntax in scripts + parallel node-gyp
  script/bundled-node-version.js
  script/check-version.js
  script/download-node.js
  script/postinstall.cmd
  script/postinstall.js
  script/postinstall.sh
Labels: Modernization
